<?php
/*
    cookies & sessions
    
    --  --  [ cookies ]

    examples
    -- popup
    -- custom settings
    -- remember me => login 

    setcookie( name <requird> , value , expire , path , domain , secure , http_only );
    -- name
    -- value
    -- expire
    -- path
    -- domain
    -- secure
    -- http_only

    modify

    delete

    add array

    --  --  [ sessions ]

    session is stored on server

    session store only a user key in cookie to know it is you

    key are generated by PHP engine so ti's almose impossible to guess

    you need to add it before any output

    advance inofrmation

    edit

    views count
*/


//cookie Ex

    if (isset($_COOKIE["background"])) {
        echo
        "<style>
                    body {
                        background-color:" . $_COOKIE["background"] . "
                    }
                </style>";
    }

    if ($_SERVER["REQUEST_METHOD"] == "POST") {
        setcookie("background", $_POST["bg-color"], strtotime("+1 hour"));
        header("location: " . $_SERVER["REQUEST_URI"]); // for refresh
    }
    ?>

    <form action="" method="post">
        <p> <input type="radio" name="bg-color" id="theme" value="#444555"><span> dark</span>
        <input type="radio" name="bg-color" id="theme" value="#eeeeee"><span> light</span></p>
        <input type="submit" value="ok">
    </form>

<?php

    //session Ex
    //note *** it is must be the first in the code 

    session_start();

    $_SESSION['name']="Mohammad";
    $_SESSION['id']=1005;

    echo "<pre>";
    print_r($_SESSION);
    echo "/<pre>";

    echo '<a href="index.php">test</a>';
?>